#!/usr/bin/env python3
"""Build a static review site. No network or third-party packages."""
from pathlib import Path
from html import escape
import json, re
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'public'
NAV=[('Inicio','/'),('Formación','/formacion/'),('Empresas','/pymes/'),('Proyectos','/proyectos/'),('Actualidad','/blog/'),('Sobre mí','/sobre-mi/')]
PAGES={}
def register(path,title,description,body,kind='WebPage'):
 PAGES[path]={'title':title,'description':description,'body':body,'kind':kind}
def button(text,url,primary=False):return f'<a class="btn {"primary" if primary else ""}" href="{url}">{text} <span aria-hidden="true">↗</span></a>'
def eyebrow(t):return f'<p class="eyebrow">{t}</p>'
def subhero(title,desc,label='Educando con chIspA'):
 return f'<section class="subhero"><div class="wrap"><div class="breadcrumb"><a href="/">Inicio</a> / {label}</div>{eyebrow(label)}<h1>{title}</h1><p>{desc}</p></div></section>'
def block(body,classes=''):return f'<section class="block {classes}"><div class="wrap">{body}</div></section>'
def card(title,description,url,label='Explorar'):
 return f'<article class="detail-card reveal"><h2>{title}</h2><p>{description}</p><a class="text-link" href="{url}">{label} <span aria-hidden="true">↗</span></a></article>'
def faq(items):return '<div class="faq">'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)+'</div>'
cta='<section class="contact-strip"><div class="wrap"><h2>Tu contexto es el<br><span class="italic">punto de partida.</span></h2>'+button('Hablemos de tu proyecto','/contacto/')+'</div></section>'
steps=block(eyebrow('Cómo trabajamos')+'<h2>Primero entender.<br>Después construir.</h2><div class="steps">'+''.join(f'<div><strong>0{i}</strong><h3>{t}</h3><p>{d}</p></div>' for i,(t,d) in enumerate([('Contexto','Identificamos el problema, las personas y las restricciones.'),('Prioridades','Elegimos un alcance útil y acordamos qué debe mejorar.'),('Prueba real','Construimos, probamos contigo y ajustamos la solución.'),('Transferencia','Documentación, formación y un mantenimiento definido.')],1))+'</div>')
articles=[('Conversación con Flor','IA en idiomas: el criterio docente sigue al mando','Una conversación sobre preparación de clases, feedback, storytelling y decisiones que siguen siendo del profesor.','/blog/ia-idiomas-flor/'),('Guía práctica','Antes de automatizar, hazte estas cinco preguntas','Un punto de partida para decidir qué proceso merece una solución y qué necesitas para mantenerla.','/blog/antes-de-automatizar/'),('Próxima conferencia · 29 octubre','Docentes con criterio en la era de la IA','Participación prevista en la XVI Semana Internacional e-Learning de UNAD Zona Sur.','/charlas/')]
def articlecards():return '<div class="editorial">'+''.join(f'<article class="article-card reveal"><small>{l}</small><h3><a href="{u}">{t}</a></h3><p>{d}</p><a class="text-link" href="{u}">Leer más <span aria-hidden="true">↗</span></a></article>' for l,t,d,u in articles)+'</div>'
home=f'''<section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">IA aplicada · formación · soluciones digitales</p><div class="hero-dash"></div><h1>De la idea a<br><span class="accent italic">lo que funciona.</span></h1><p class="hero-lead">Ayudo a docentes, empresas y organizaciones a convertir la inteligencia artificial en aprendizaje, procesos útiles y soluciones que se pueden usar.</p><p class="hero-lead">Empezamos por tu contexto. Avanzamos con <span class="rotating" aria-hidden="true">la formación</span><span class="sr-only" style="position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)">formación, automatización, prototipos e implementación.</span></p><div class="hero-actions">{button('Encuentra tu punto de partida','/contacto/',True)}{button('Ver soluciones','#soluciones')}</div><p class="audience">Tarazona · Aragón · proyectos online</p></div><div class="portrait"><img class="portrait-image" src="/assets/jose-latorre.jpg" alt="José Luis Latorre Delgado, docente, formador y consultor en IA aplicada" width="600" height="600" fetchpriority="high"><span class="portrait-index">PERSONAS + CRITERIO + TECNOLOGÍA</span><div class="portrait-note">“La tecnología ayuda.<br>La chIspA la pones tú.”<small>José Luis Latorre · Educando con chIspA</small></div></div></div></section><div class="signal"><div class="wrap"><span><strong>Aula real</strong> · experiencia educativa</span><span><strong>IA con criterio</strong> · método CHISPA</span><span><strong>Procesos útiles</strong> · soluciones a medida</span></div></div>'''
home+=block('<div class="heading" id="soluciones"><div>'+eyebrow('01 / Qué podemos resolver')+'<h2>Distintos contextos.<br><span class="italic">Una forma de trabajar.</span></h2></div><p>Elige el problema que quieres resolver. La herramienta viene después.</p></div><div class="service-grid">'+''.join(f'<article class="service reveal"><span class="num">0{i} / {tag}</span><h3>{title}</h3><p>{desc}</p><a class="text-link" href="{url}">{link}<span aria-hidden="true">↗</span></a></article>' for i,(tag,title,desc,url,link) in enumerate([('APRENDIZAJE','Formación e IA educativa','Talleres, diagnóstico CHISPA y acompañamiento para docentes y centros. Del interés por la IA a decisiones con sentido.','/formacion/','Explorar formación'),('ORGANIZACIONES','Empresas y automatización','Formación de equipos, mejora de procesos, asistentes y soluciones digitales adaptadas al trabajo real.','/pymes/','Explorar soluciones'),('EXPERIENCIAS','Proyectos y gamificación','Recursos interactivos, recorridos y prototipos que convierten una idea en una experiencia participativa.','/proyectos/','Ver proyectos')],1))+'</div>')
method=[('C','Criterio','Aclarar el objetivo antes de elegir una herramienta.'),('H','Humanismo digital','Diseñar alrededor de las personas y su juicio profesional.'),('I','Implementación','Pasar de una idea a una prueba útil en el contexto real.'),('S','Seguridad','Definir datos, límites y responsabilidades desde el principio.'),('P','Productividad','Quitar fricción para dedicar tiempo a lo que aporta valor.'),('A','Automatización','Conectar tareas cuando el proceso ya está bien entendido.')]
home+=block('<div class="method-grid"><div class="sticky-copy">'+eyebrow('02 / Método CHISPA')+'<h2>Una brújula.<br><span class="italic">Seis criterios.</span></h2><p>Para una clase, un equipo o un proyecto digital: primero el para qué, después la tecnología.</p>'+button('Conocer mi enfoque','/sobre-mi/')+'</div><div class="method-steps">'+''.join(f'<div class="method-step reveal"><span class="letter">{l}</span><div><h3>{t}</h3><p>{d}</p></div></div>' for l,t,d in method)+'</div></div>','paper')
home+=block('<div class="heading"><div>'+eyebrow('03 / De la idea a la experiencia')+'<h2>Soluciones que<br><span class="italic">se pueden explorar.</span></h2></div><p>La forma de una solución cambia con el contexto: una ruta, un recurso, un sistema o una sesión.</p></div><div class="projects"><article class="project feature reveal"><span class="project-tag">Patrimonio · storytelling · participación</span><h3>El Pergamino de<br>las Tres Culturas</h3><p>Una experiencia digital para descubrir Tarazona a través de retos y narrativa. Explora la página informativa de la versión actual.</p><a class="text-link" href="https://educandoconchispa.com/ruta-pergamino-3-culturas-Tarazona/info.html">Descubrir la experiencia <span aria-hidden="true">↗</span></a></article><article class="project reveal"><span class="project-tag">Aula · diseño · interacción</span><h3>El recurso adecuado.<br>En el momento adecuado.</h3><p>Juegos, actividades, materiales y prototipos diseñados a partir de un objetivo de aprendizaje, con el docente al mando.</p><a class="text-link" href="/proyectos/">Ver formas de trabajar <span aria-hidden="true">↗</span></a></article></div>')
home+='<div class="quote-band"><div class="wrap"><p class="quote">“La IA analiza datos.<br>Los profes encendemos <span class="accent italic">la chIspA.</span>”</p><small>EXPERIENCIA EDUCATIVA · VISIÓN TRANSVERSAL</small></div></div>'
home+=block('<div class="heading"><div>'+eyebrow('04 / Ideas, conversaciones y encuentros')+'<h2>La chIspA<br><span class="italic">también se comparte.</span></h2></div>'+button('Ver actualidad','/blog/')+'</div>'+articlecards())+cta
register('/','Educando con chIspA | Formación, IA y automatización con criterio','Formación, consultoría en IA, automatización y soluciones digitales para docentes, empresas y organizaciones. José Luis Latorre, Tarazona y online.',home)
services=[('Formación de equipos','Para empresas y organizaciones que quieren pasar del uso individual a un criterio común.','Taller adaptado, ejercicios con tareas reales y una guía de buenas prácticas.','Sesiones introductorias, productividad, verificación de resultados y uso responsable.'),('Diagnóstico y mejora de procesos','Para equipos que invierten demasiado tiempo en coordinación, documentos o tareas repetidas.','Mapa de proceso, prioridades y propuesta de alcance con dependencias y límites.','Gestión de consultas, preparación de documentos y coordinación de información.'),('Automatización e integración','Para procesos definidos que necesitan conectar herramientas y reducir pasos manuales.','Flujo probado, documentación y criterios de seguimiento y mantenimiento.','Formularios, archivos, avisos internos y sincronización de información.'),('Soluciones digitales a medida','Para una necesidad que no encaja en una herramienta estándar.','Prototipo funcional, revisión contigo y plan de evolución si merece continuar.','Paneles, asistentes internos, generadores y pequeñas aplicaciones.'),('Diseño formativo y FPE','Para centros y profesionales que necesitan recursos coherentes con un programa de aprendizaje.','Estructura de contenidos, actividades y evaluaciones revisables; formato de entrega acordado.','Materiales para teleformación, rúbricas y recursos reutilizables.')]
companies=subhero('Menos fricción.<br><span class="accent italic">Más capacidad para tu equipo.</span>','Formación, IA y automatización para empresas y organizaciones. Soluciones prácticas que parten del proceso, las personas y el resultado que necesitas.','Empresas y organizaciones')
companies+=block('<div class="content-grid">'+''.join(f'<article class="detail-card reveal"><p class="eyebrow">0{i} / Solución</p><h2>{t}</h2><p>{a}</p><p><strong>Qué entregamos</strong><br>{e}</p><p><strong>Ejemplos de alcance</strong><br>{ex}</p><a class="text-link" href="/contacto/">Cuéntame tu contexto <span aria-hidden="true">↗</span></a></article>' for i,(t,a,e,ex) in enumerate(services,1))+'</div>')+steps
companies+=block(eyebrow('Preguntas de empresas y FPE')+'<h2>Antes de dar el paso.</h2>'+faq([('¿Tiene que ser un proyecto grande?','Podemos empezar por un proceso concreto o un taller. El alcance y los entregables se acuerdan antes de construir.'),('¿Qué información necesitas para valorar mi caso?','Qué hace hoy el equipo, dónde aparece la fricción, qué herramientas utiliza y qué resultado esperas. No compartas contraseñas ni datos sensibles por el formulario.'),('¿Se puede utilizar lo que ya tenemos?','Revisamos las herramientas actuales y sus posibilidades de integración antes de proponer nuevas suscripciones.'),('¿Incluye mantenimiento?','Se define por separado según la solución: qué revisar, quién responde y qué cambios quedan fuera. Una automatización requiere seguimiento.'),('¿Garantizas un ahorro concreto?','El impacto se comprueba con una referencia inicial y una prueba real. No se promete un porcentaje de ahorro antes de conocer el proceso.'),('¿Trabajas solo con educación?','La experiencia docente aporta método, formación y transferencia. También trabajo en procesos y soluciones para empresas y organizaciones.')]))+cta
register('/pymes/','IA y automatización para empresas | Educando con chIspA','Formación de equipos, diagnóstico de procesos, automatización, soluciones digitales y materiales FPE. Trabajo práctico y alcance a medida.',companies)
education=subhero('La IA analiza datos.<br><span class="accent italic">Los profes encendemos la chIspA.</span>','Formación e inteligencia artificial para docentes, academias y centros. Un enfoque que parte del aula real, del criterio pedagógico y de límites claros.','Formación e IA educativa')
education+=block('<div class="content-grid">'+card('Diagnóstico CHISPA','Un punto de partida para ordenar el uso de IA, identificar necesidades y priorizar los siguientes pasos.','/contacto/','Solicitar diagnóstico')+card('Formación docente aplicada','Talleres que conectan planificación, materiales, evaluación y feedback con situaciones reales de enseñanza.','/contacto/','Hablar de una formación')+card('Formación para centros','Una propuesta adaptada al equipo, sus objetivos y su punto de partida. Casos de uso y criterios compartidos.','/contacto/','Cuéntame cómo es tu centro')+card('Recursos y acompañamiento','Diseño de materiales, experiencias y procesos con revisión docente y transferencia al trabajo cotidiano.','/proyectos/','Explorar posibilidades')+'</div>')+steps
education+=block(eyebrow('Preguntas frecuentes')+'<h2>Decidir con información.</h2>'+faq([('¿Qué incluye el Diagnóstico CHISPA?','Autoevaluación del centro, semáforo pedagógico antes, durante y después, y recomendaciones de primeros pasos ajustadas al contexto.'),('¿Cuánto se tarda en completarlo?','La versión actual propone entre 20 y 30 minutos. Si participa un equipo de dirección, coordinación y docentes, ayuda a recoger distintas perspectivas.'),('¿Cómo se cuida la protección de datos?','Se evita solicitar datos sensibles del alumnado. Los ejemplos deben anonimizarse y revisarse; las condiciones de cada herramienta y tratamiento se valoran según el caso.'),('¿Sirve si el claustro todavía no usa IA?','Sí. Permite definir objetivos, criterios y límites antes de generalizar el uso de herramientas.'),('¿Qué recibo después?','Un resumen con prioridades: qué abordar primero, qué evitar y qué pasos encajan en los recursos y objetivos del centro.'),('¿El diagnóstico es gratuito?','La propuesta actual ofrece una primera entrada gratuita. Si necesitas formación o acompañamiento, el alcance posterior se acuerda por separado.')]))+cta
register('/formacion/','Formación en IA para docentes y centros | Educando con chIspA','Formación en IA educativa con criterio pedagógico, diagnóstico CHISPA y acompañamiento. Docentes y centros en Tarazona, Aragón y online.',education)
projects=subhero('Cada problema pide<br><span class="accent italic">su propia solución.</span>','Experiencias y líneas de trabajo que combinan diseño, formación y tecnología. Lo útil es comprender qué cambia para las personas que las utilizan.','Proyectos')
projects+=block('<div class="content-grid">'+card('El Pergamino de las Tres Culturas','Experiencia digital de patrimonio y narrativa en Tarazona. Retos y participación para explorar la ciudad. La página informativa actual está disponible en la web original.','https://educandoconchispa.com/ruta-pergamino-3-culturas-Tarazona/info.html','Ver la experiencia actual')+card('Recursos interactivos para aprender','Una actividad o juego empieza por lo que el alumnado necesita practicar. Diseño y adaptación de materiales con intención pedagógica.','/contacto/','Diseñar un recurso')+card('Procesos y soluciones para equipos','De una tarea repetida a un flujo claro: formularios, documentos, avisos, asistentes o paneles según el contexto.','/pymes/','Ver servicios para organizaciones')+card('Formación que se puede aplicar','Sesiones y recursos para que el equipo comprenda una solución, la pruebe y sepa cuándo necesita revisión.','/formacion/','Ver formación')+'</div><p class="notice">Las líneas de trabajo describen posibilidades de servicio. No representan resultados medidos ni casos de clientes sin autorización.</p>')+cta
register('/proyectos/','Proyectos y soluciones aplicadas | Educando con chIspA','Gamificación, recursos interactivos y soluciones digitales. Experiencias para educación, organizaciones y territorio.',projects)
blog=subhero('Ideas que nacen<br><span class="accent italic">del trabajo real.</span>','Conversaciones, reflexiones y encuentros sobre IA, aprendizaje y mejora de procesos.','Actualidad y blog')+block(articlecards())+block('<div class="detail-card">'+eyebrow('Charlas y encuentros')+'<h2>Compartir criterio también es parte del trabajo.</h2><p>Consulta la próxima participación prevista en UNAD y la conversación con Flor sobre IA aplicada a idiomas.</p>'+button('Ver charlas','/charlas/')+'</div>')+cta
register('/blog/','Actualidad y blog de IA aplicada | Educando con chIspA','Conversaciones, guías y encuentros sobre inteligencia artificial, criterio docente y automatización. José Luis Latorre.',blog)
flor=subhero('IA en idiomas:<br><span class="accent italic">el criterio sigue al mando.</span>','Una conversación con Flor, de Enseñar Español Online, sobre el trabajo cotidiano de los profesores de idiomas.','Conversación con Flor')
flor+=block('''<article class="prose"><p>Preparar actividades y revisar feedback son tareas donde la IA puede ayudar. En la conversación con Flor, el hilo conductor fue el papel del profesor para definir objetivos y adaptar los recursos a su grupo.</p><h2>Del recurso a la decisión pedagógica</h2><p>Planificación, storytelling y carga administrativa fueron algunos de los temas tratados. La oportunidad está en revisar qué merece llegar al aula y qué necesita intervención docente.</p><h2>Ver la entrevista</h2><p>El vídeo completo está disponible en el canal de Flor. Lo enlazamos sin cargar un reproductor externo ni cookies de YouTube en esta página.</p><a class="btn primary" href="https://youtu.be/8vTyL7V3d7k">Ver la conversación en YouTube ↗</a><p class="source">Fuente: <a href="https://es.linkedin.com/posts/jose-luis-latorre-delgado_iaeducativa-ele-formaci%C3%B3ndocente-activity-7455135785722421248-gNgI">publicación de José Luis Latorre sobre la entrevista</a>. Texto editorial elaborado para esta web; no es una transcripción.</p><div class="inline-links"><a href="/formacion/">Formación para docentes</a><a href="/blog/">Volver a actualidad</a></div></article>''')+cta
register('/blog/ia-idiomas-flor/','IA en idiomas: conversación con Flor | Educando con chIspA','Conversación con Flor de Enseñar Español Online sobre IA, planificación, feedback y criterio docente. Enlace a la entrevista completa.',flor,'Article')
practical=subhero('Antes de automatizar,<br><span class="accent italic">hazte cinco preguntas.</span>','Una guía para empezar con un proceso concreto, expectativas realistas y una responsabilidad definida.','Guía práctica')
practical+=block('''<article class="prose"><p>Automatizar no empieza conectando aplicaciones. Empieza comprendiendo cómo funciona una tarea y qué debería mejorar para las personas que la realizan.</p><h2>1. ¿Qué problema quiero resolver?</h2><p>Describe una fricción observable: información que se copia varias veces, documentos que se preparan manualmente o consultas que se pierden. Acota un proceso antes de pensar en un sistema completo.</p><h2>2. ¿Está claro cómo se hace hoy?</h2><p>Identifica quién inicia la tarea, qué información necesita y qué resultado espera. Si el proceso cambia cada vez, primero conviene ordenar criterios y excepciones.</p><h2>3. ¿Qué datos necesita?</h2><p>Utiliza solo la información necesaria y decide quién puede acceder. Antes de enviar datos a una herramienta, revisa sus condiciones y la finalidad del tratamiento.</p><h2>4. ¿Cómo sabré que mejora?</h2><p>Elige una referencia inicial: tiempo por tarea, consultas sin respuesta o errores que requieren revisión. Prueba con un alcance pequeño y compara resultados sin confundir una demostración con el trabajo real.</p><h2>5. ¿Quién lo mantendrá?</h2><p>Una integración puede cambiar, un permiso puede caducar y una excepción puede necesitar intervención humana. Acuerda responsable, documentación y una forma clara de detectar errores.</p><blockquote>Un proceso pequeño bien entendido es un buen lugar para empezar.</blockquote><p>Autor: José Luis Latorre Delgado · Educando con chIspA.</p><div class="inline-links"><a href="/pymes/">Soluciones para empresas</a><a href="/contacto/">Valorar mi proceso</a></div></article>''')+cta
register('/blog/antes-de-automatizar/','Cinco preguntas antes de automatizar | Educando con chIspA','Una guía práctica para decidir qué automatizar: problema, proceso, datos, impacto y mantenimiento. Para empresas y organizaciones.',practical,'Article')
events=subhero('Conversaciones que<br><span class="accent italic">encienden nuevas ideas.</span>','Charlas y encuentros para compartir experiencias, preguntas y criterio sobre IA aplicada.','Charlas y eventos')
events+=block('''<article class="event"><div class="event-date">29<small>OCTUBRE · 2026</small></div><div><span class="status">Participación prevista</span><h2 style="margin-top:20px">Docentes con criterio en la era de la IA</h2><p>Inteligencia humana-aumentada, seguridad y creatividad en contextos educativos.</p><p><strong>XVI Semana Internacional e-Learning · UNAD Zona Sur</strong></p><p>15:00 Colombia · 21:00 España peninsular<br>Duración prevista: 45–50 minutos.</p><p class="form-note">Información de la invitación recibida. Los datos de acceso para asistentes se incorporarán cuando sean públicos.</p></div></article>''')+block('<div class="content-grid">'+card('Conversación con Flor','IA aplicada a la enseñanza de idiomas, preparación de clases y decisiones docentes. Entrevista disponible en YouTube.','/blog/ia-idiomas-flor/','Ver la conversación')+card('¿Organizas un encuentro?','Podemos adaptar una sesión a docentes, centros, empresas u organizaciones, con objetivos y duración acordados.','/contacto/','Proponer una charla')+'</div>')+cta
register('/charlas/','Charlas y encuentros sobre IA | Educando con chIspA','Próxima participación en UNAD y entrevista con Flor. Charlas sobre IA, seguridad, creatividad y criterio docente.',events,'CollectionPage')
about=subhero('José Luis<br><span class="accent italic">Latorre Delgado.</span>','Docente, formador y consultor en IA aplicada. Conecto experiencia educativa, diseño de soluciones y mejora de procesos.','Sobre mí')
about+=block('''<div class="about-layout"><article class="prose"><p class="eyebrow">Experiencia educativa · visión transversal</p><h2>Primero el para qué.<br>Después la herramienta.</h2><p>Mi punto de partida es el trabajo con personas que aprenden, enseñan y necesitan resolver problemas concretos. Esa mirada guía tanto una formación como el diseño de una solución digital.</p><p>Educando con chIspA reúne formación, recursos, IA aplicada, automatización y experiencias interactivas. El objetivo es que la tecnología ayude a trabajar con más criterio y que la solución tenga sentido en el día a día.</p><h2>Del aula a las organizaciones</h2><p>La experiencia docente aporta capacidad para escuchar, estructurar, explicar y comprobar que lo aprendido se puede utilizar. Esa base también es útil para acompañar equipos, ordenar procesos y hacer comprensibles nuevas herramientas.</p><p>Trabajo desde Tarazona, Zaragoza, con proyectos en Aragón, Ribera Navarra y formato online.</p><div class="inline-links"><a href="https://www.linkedin.com/in/jose-luis-latorre-delgado">Mi trayectoria en LinkedIn</a><a href="/contacto/">Hablar conmigo</a></div></article><div><img class="about-photo" src="/assets/jose-latorre.jpg" alt="José Luis Latorre Delgado" width="600" height="600" loading="lazy"><p class="mini-stat"><strong>CHISPA</strong><br>Criterio · Humanismo digital · Implementación<br>Seguridad · Productividad · Automatización</p></div></div>''')+cta
register('/sobre-mi/','José Luis Latorre Delgado | Educando con chIspA','Docente, formador y consultor en IA aplicada, automatización y soluciones digitales. Tarazona, Zaragoza, Aragón y online.',about,'ProfilePage')
contact=subhero('Cuéntame qué<br><span class="accent italic">necesitas resolver.</span>','Una formación, un proceso o una idea de proyecto. Empezamos con el contexto y buscamos un alcance que tenga sentido.','Contacto')
contact+=block('<div class="detail-card"><p class="eyebrow">Recurso educativo</p><h2>Solicita el PDF de Educando con chIspA</h2><p>Accede al formulario educativo para solicitar el recurso por correo.</p><a class="btn primary" href="https://ia.educandoconchispa.com/#contacto">Ir al formulario del PDF ↗</a></div>')
contact+=block('''<div class="contact-grid"><div><p class="eyebrow">Contacto directo</p><h2>Hablemos con<br>un objetivo claro.</h2><div class="contact-list"><a href="mailto:educandoconchispa@gmail.com">educandoconchispa@gmail.com</a><a href="tel:+34690982522">690 982 522</a><a href="https://www.linkedin.com/in/jose-luis-latorre-delgado">LinkedIn ↗</a></div><p class="form-note">Tarazona, Zaragoza · Aragón y online</p><p class="form-note">No incluyas contraseñas ni datos personales del alumnado, clientes o terceros en tu consulta.</p><p><a href="https://ia.educandoconchispa.com/privacidad.html" style="text-decoration:underline">Consultar la política de privacidad actual</a></p></div><form id="contact-draft"><h2 style="font-size:26px">Prepara tu consulta</h2><p class="form-note">Este asistente prepara un borrador en tu correo. No envía ni guarda los datos en esta web.</p><label for="name">Tu nombre</label><input id="name" name="name" maxlength="100" autocomplete="name" required><label for="context">¿En qué contexto?</label><select id="context" name="context"><option>Docente o centro educativo</option><option>Empresa u organización</option><option>Centro o profesional de FPE</option><option>Proyecto de territorio o evento</option><option>Otro contexto</option></select><label for="message">¿Qué necesitas y qué haces hoy?</label><textarea id="message" name="message" maxlength="1800" required></textarea><p class="form-note">Al pulsar preparar, verás un enlace para abrir tu aplicación de correo. El envío lo decides tú allí.</p><button class="btn primary" type="submit">Preparar borrador <span aria-hidden="true">↗</span></button><div id="draft-result" class="form-result" role="status" hidden></div><noscript><p>Para contactar, escribe a <a href="mailto:educandoconchispa@gmail.com">educandoconchispa@gmail.com</a>. El asistente de borrador necesita JavaScript.</p></noscript></form></div>''')
register('/contacto/','Contacto | Educando con chIspA','Contacta con José Luis Latorre para formación, IA, automatización o soluciones digitales. Consulta por email, teléfono o LinkedIn.',contact)
register('/404/','Página no encontrada | Educando con chIspA','Encuentra la formación, las soluciones o los contenidos de Educando con chIspA.',subhero('Esta ruta no<br><span class="accent italic">lleva a una página.</span>','Puedes volver al inicio o explorar los servicios.','Página no encontrada')+block(button('Volver al inicio','/',True)))
for path,d in PAGES.items():
 depth=len([x for x in path.split('/') if x]); prefix='../'*depth or './'
 def localize(s):
  def href(m):
   target=m.group(1); base,sep,anchor=target.partition('#')
   if base.endswith('/'):base+='index.html'
   return 'href="'+prefix+base.lstrip('/')+(('#'+anchor) if sep else '')+'"'
  return re.sub(r'href="(/[^"]*)"',href,s).replace('src="/','src="'+prefix)
 url='https://educandoconchispa.com'+path
 person={'@type':'Person','@id':'https://educandoconchispa.com/#jose','name':'José Luis Latorre Delgado','url':'https://educandoconchispa.com/sobre-mi/','sameAs':['https://www.linkedin.com/in/jose-luis-latorre-delgado']}
 org={'@type':'Organization','@id':'https://educandoconchispa.com/#organization','name':'Educando con chIspA','url':'https://educandoconchispa.com/','logo':'https://educandoconchispa.com/assets/logo.svg','founder':{'@id':person['@id']}}
 node={'@type':d['kind'],'@id':url+'#page','url':url,'name':d['title'],'description':d['description'],'inLanguage':'es','publisher':{'@id':org['@id']}}
 if d['kind']=='Article':node.update({'headline':d['title'],'author':{'@id':person['@id']}})
 links=''.join(f'<a href="{u}"'+(' aria-current="page"' if u==path else '')+f'>{t}</a>' for t,u in NAV)
 head=f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(d['title'])}</title><meta name="description" content="{escape(d['description'],quote=True)}"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#071015"><link rel="canonical" href="{url}"><meta property="og:title" content="{escape(d['title'],quote=True)}"><meta property="og:description" content="{escape(d['description'],quote=True)}"><meta property="og:type" content="{'article' if d['kind']=='Article' else 'website'}"><meta property="og:url" content="{url}"><meta property="og:image" content="https://educandoconchispa.com/assets/og.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':[person,org,node]},ensure_ascii=False)}</script></head>'''
 shell=f'''<body><a class="skip" href="#main">Saltar al contenido</a><header class="topbar"><div class="wrap nav"><a class="brand" href="/" aria-label="Educando con chIspA, inicio"><img src="/assets/logo.svg" width="275" height="70" alt="Educando con chIspA"></a><button class="menu" aria-controls="navigation" aria-expanded="false" type="button">Menú</button><nav id="navigation" class="links" aria-label="Navegación principal">{links}<a class="nav-cta" href="/contacto/">Hablemos ↗</a></nav></div></header><main id="main">{d['body']}</main><footer class="footer"><div class="wrap"><div class="footer-top"><div><strong>EDUCANDO CON chIspA</strong><br>La tecnología ayuda. La chIspA la pones tú.</div><div class="footer-links"><a href="/charlas/">Charlas</a><a href="/contacto/">Contacto</a><a href="https://www.linkedin.com/in/jose-luis-latorre-delgado">LinkedIn</a><a href="https://ia.educandoconchispa.com/privacidad.html">Privacidad actual</a></div></div><div class="footer-bottom"><span>© 2026 Educando con chIspA · Tarazona, Zaragoza</span><button class="motion-control" type="button" aria-pressed="false">Pausar movimiento</button></div></div></footer></body></html>'''
 directory=OUT/path.strip('/');directory.mkdir(parents=True,exist_ok=True);(directory/'index.html').write_text(localize(head+shell),encoding='utf-8')
(OUT/'404.html').write_text((OUT/'404/index.html').read_text().replace('../','./'))
(OUT/'robots.txt').write_text('User-agent: *\nDisallow: /\n')
# Candidate sitemap is documentation only: not served from staging.
(ROOT/'docs/sitemap.production-candidate.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>https://educandoconchispa.com{p}</loc></url>\n' for p in PAGES if p!='/404/')+'</urlset>\n')
print(f'Built {len(PAGES)} pages + 404.html; staging noindex enabled.')
